import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\ai_impact_jobs_2010_2025.csv",encoding="latin1")

# print(df.head())
# print(df.info())
df['Salary']=df['salary_usd'].fillna(df['salary_usd'].mean())
df['Ai_adoption_stage']=df['industry_ai_adoption_stage']
df=df.drop('industry_ai_adoption_stage',axis=1)
df=df.drop('salary_usd',axis=1)
# print(df.columns)
df.columns = df.columns.str.capitalize()
# print(df.columns)
# print(df.duplicated().sum())
# print(df.columns.tolist())
# print(df.head(2))
# print(df.isnull().sum())
# print(df.duplicated().sum())
# print(df['Industry'].value_counts().head(10))
# print(df['Ai_job_displacement_risk'].value_counts())
# print(df['Ai_adoption_stage'].value_counts())
# print(df['Reskilling_required'].value_counts())

# print(df[['Salary', 'Ai_intensity_score', 'Automation_risk_score', 'Salary_change_vs_prev_year_percent']].describe())
df['Ai_keywords']=df['Ai_keywords'].fillna("None")
df['Ai_skills']=df['Ai_skills'].fillna("None")
# print(df.isnull().sum().sum())  # should print 0

# print(df['Industry'].value_counts().head(10))
# print(df['Ai_job_displacement_risk'].value_counts())
# print(df['Ai_adoption_stage'].value_counts())
# print(df['Reskilling_required'].value_counts())
# print(df[['Industry','Reskilling_required']])
# result=df.groupby('Industry')['Reskilling_required'].sum()
# result=df.groupby('Industry')['Reskilling_required'].sum().sort_values(ascending=False).reset_index()
colors = [ '#e74c3c', '#2ecc71', '#3498db', '#f39c12', '#9b59b6', '#1abc9c', '#e67e22', '#34495e', '#e91e63']

# plt.figure(figsize=(10,6))
# sns.barplot(x='Industry', y='Reskilling_required', data=result, palette=colors)
# plt.title('Reskilling Required by Industry')
# plt.xlabel('Industry')
# plt.ylabel('Number of Jobs Needing Reskilling')
# plt.xticks(rotation=45)
# plt.ylim(0, 300)

# for i, v in enumerate(result['Reskilling_required']):
#     plt.text(i, v + 2, str(v), ha='center', fontweight='bold', fontsize=12)
# plt.tight_layout()
# plt.savefig(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\chart1_reskilling.png", dpi=150, bbox_inches='tight')
# # plt.show()

# //chart 2 
result2=df['Ai_job_displacement_risk'].value_counts()
print(df['Ai_job_displacement_risk'].value_counts())

# plt.figure(figsize=(10,6))
# colors2=['green','yellow','red']
# plt.pie(result2.values, labels=result2.index, autopct='%1.1f%%', colors=colors2)
# plt.title("AI Job Displacement Risk")
# plt.savefig(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\chart3_ai_job_displacement_risk.png", dpi=150, bbox_inches='tight')
# plt.show()
# result3=df['Ai_adoption_stage'].value_counts()
# print(df['Ai_adoption_stage'].value_counts())
# plt.figure(figsize=(10,6))
# sns.boxplot(x='Ai_adoption_stage', y='Salary', data=df)
# plt.title("AI Adoption Stage")
# plt.xlabel('Categories')
# plt.ylabel('Values')
# plt.tight_layout()
# plt.show()

# result4=df.groupby('Industry')['Automation_risk_score'].mean().sort_values(ascending=True).reset_index()
# print(result4)
# sns.barplot(x='Automation_risk_score', y='Industry', data=result4, palette=colors)
# plt.figure(figsize=(10,6))
# sns.barplot(x='Automation_risk_score',y='Industry',data=result4,palette=colors)
# plt.title('Automation Risk Score')
# plt.xlabel('Risk Score')
# plt.ylabel('Industry')
# for i, v in enumerate(result4['Automation_risk_score']):
#     plt.text(v + 0.002, i, f'{v:.3f}', va='center', fontweight='bold', fontsize=10)
# plt.tight_layout()
# plt.savefig(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\chart4_automation_risk_score.png", dpi=150, bbox_inches='tight')
# # plt.show()
# print(df.columns.tolist())
print(df['Posting_year'].value_counts().sort_index())
result5 = df['Posting_year'].value_counts().sort_index().reset_index() 
print(result5)
plt.figure(figsize=(10, 6))
sns.lineplot(x='Posting_year', y='count', data=result5, color='steelblue', marker='o')
plt.title("Job Posting / Year ")
plt.xlabel('Year')
plt.ylabel('Number of Job Postings')
plt.tight_layout()
plt.savefig(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\chart5_job_postings.png", dpi=150, bbox_inches='tight')
# plt.show()
df['Reskilling_count'] = df['Reskilling_required'].astype(int)
df.to_csv(r"C:\Users\HP\OneDrive - Higher Education Commission\Desktop\python\global ai impact\cleaned_ai_jobs.csv", index=False)
print("CSV saved!")